<?php
/**
 * Helper utilities.
 *
 * @package CreativeDBS\CampMgmt
 */
namespace CreativeDBS\CampMgmt;

defined( 'ABSPATH' ) || exit;

class Helpers {

	public static function sanitize_deep( $value ) {
		if ( is_array( $value ) ) {
			return array_map( [ __CLASS__, __FUNCTION__ ], $value );
		}
		if ( is_scalar( $value ) ) {
			return sanitize_text_field( wp_unslash( (string) $value ) );
		}
		return $value;
	}

	public static function get_post_sanitized(){
		return isset( $_POST ) ? self::sanitize_deep( $_POST ) : []; // phpcs:ignore WordPress.Security.NonceVerification.Missing
	}

	public static function get_get_sanitized(){
		return isset( $_GET ) ? self::sanitize_deep( $_GET ) : []; // phpcs:ignore WordPress.Security.NonceVerification.Missing
	}

	public static function nonce_field($action ){
		wp_nonce_field( $action );
	}

	public static function verify_or_die($action ){
		if ( empty( $_REQUEST['_wpnonce'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}
		$nonce = sanitize_text_field( wp_unslash( $_REQUEST['_wpnonce'] ) );
		if ( ! wp_verify_nonce( $nonce, $action ) ) {
			wp_die( esc_html__( 'Security check failed.', 'creativedbs-camp-mgmt' ) );
		}
	}

	public static function require_cap($cap = 'manage_options' ){
		if ( ! current_user_can( $cap ) ) {
			wp_die( esc_html__( 'Insufficient permissions.', 'creativedbs-camp-mgmt' ) );
		}
	}


	/**
	 * Format a website URL as a clickable link showing only the domain (no www.).
	 *
	 * @param string $url Full URL.
	 * @return string HTML link or empty string.
	 */
	public static function format_website_link( $url ) {
		if ( empty( $url ) ) { return ''; }
		$url = trim( (string) $url );
		if ( ! preg_match( '#^https?://#i', $url ) ) { $url = 'https://' . $url; }
		$href = esc_url( $url ); if ( ! $href ) { return ''; }
		$host = parse_url( $href, PHP_URL_HOST ); if ( ! $host ) { $host = $href; }
		$display = preg_replace( '/^www\\./i', '', $host );
		return sprintf('<a href="%1$s" target="_blank" rel="noopener">%2$s</a>', $href, esc_html( $display ) );
	}



	/**
	 * Render a small logo image if URL is present.
	 *
	 * @param string $url  Logo URL.
	 * @param int    $size Square size in px (default 36).
	 * @return string <img> HTML or empty string.
	 */
	public static function format_logo_img( $url, $size = 36 ) {
		$url = trim( (string) $url ); if ( empty( $url ) ) { return ''; }
		$src = esc_url( $url ); if ( ! $src ) { return ''; }
		$size = max( 16, intval( $size ) );
		return sprintf('<img src="%1$s" alt="" style="width:%2$dpx;height:%2$dpx;object-fit:contain;border-radius:6px;background:#fff;box-shadow:0 0 0 1px rgba(0,0,0,.06);" />', $src, $size );
	}



	/**
	 * Return a small logo image. If no explicit logo URL, use the site's favicon derived from Website URL.
	 *
	 * @param string $logo_url    Logo URL (if available).
	 * @param string $website_url Website URL (used for favicon fallback).
	 * @param string $camp_name   Alt text.
	 * @param int    $size        Square size in px (default 36).
	 * @return string <img> HTML or empty string.
	 */
	public static function format_logo_or_favicon( $logo_url, $website_url, $camp_name = '', $size = 36 ) {
		$logo_url    = trim( (string) $logo_url );
		$website_url = trim( (string) $website_url );
		$size        = max( 16, intval( $size ) );

		if ( $website_url && ! preg_match( '#^https?://#i', $website_url ) ) {
			$website_url = 'https://' . $website_url;
		}

		$src = '';
		if ( $logo_url ) {
			$src = esc_url( $logo_url );
		}

		if ( ! $src && $website_url ) {
			$host = parse_url( $website_url, PHP_URL_HOST );
			if ( $host ) {
				$src = esc_url( 'https://www.google.com/s2/favicons?domain=' . $host . '&sz=64' );
			}
		}

		if ( ! $src ) { return ''; }

		$alt = sanitize_text_field( $camp_name );

		return sprintf(
			'<img src="%1$s" alt="%2$s" style="width:%3$dpx;height:%3$dpx;object-fit:contain;border-radius:6px;background:#fff;box-shadow:0 0 0 1px rgba(0,0,0,.06);" />',
			$src,
			esc_attr( $alt ),
			$size
		);
	}



	/**
	 * Encrypt plaintext (AES-256-CBC). Key from CDBS_CAMP_ENC_KEY or WP salts.
	 */
	public static function enc_encrypt( $plaintext ) {
		$key = defined('CDBS_CAMP_ENC_KEY') ? CDBS_CAMP_ENC_KEY : wp_salt('secure_auth');
		$key = substr(hash('sha256', (string) $key, true), 0, 32);
		$iv  = openssl_random_pseudo_bytes(16);
		$raw = openssl_encrypt( (string) $plaintext, 'aes-256-cbc', $key, OPENSSL_RAW_DATA, $iv );
		if ( false === $raw ) return '';
		return base64_encode( $iv . $raw );
	}

	/**
	 * Decrypt base64 blob generated by enc_encrypt().
	 */
	public static function enc_decrypt( $cipher_b64 ) {
		$key = defined('CDBS_CAMP_ENC_KEY') ? CDBS_CAMP_ENC_KEY : wp_salt('secure_auth');
		$key = substr(hash('sha256', (string) $key, true), 0, 32);
		$blob = base64_decode( (string) $cipher_b64, true );
		if ( false === $blob || strlen($blob) < 17 ) return '';
		$iv  = substr($blob, 0, 16);
		$raw = substr($blob, 16);
		$plain = openssl_decrypt( $raw, 'aes-256-cbc', $key, OPENSSL_RAW_DATA, $iv );
		return false === $plain ? '' : $plain;
	}

	public static function mask_secret( $text ) {
		$txt = (string) $text;
		$len = strlen( $txt );
		if ( $len <= 4 ) return str_repeat('•', $len );
		return substr($txt, 0, 2) . str_repeat('•', max(0, $len - 4)) . substr($txt, -2);
	}

}